### GET ALL Product
GET http://localhost:3000/api/user

### Insert New Product
POST http://localhost:3000/api/user
content-type: application/json

{
    "name": "Keyboard",
    "price" : 10000,
    "description" : "Hyper Sensitive Keyboard",
    "stock" : 1
}

### Detail Product
GET hhtp://localhost:3000/api/user/68ecc2774d49272f5636f31f

### Update Product
PUT http://localhost:3000/api/user/68ecc2774d49272f5636f31f
content-type: application/json

{
    "price" : "600000",
    "stock" : 5
}

### Delete Product
DELETE http://localhost:3000/api/user/68ecc2774d49272f5636f31f